name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # workflow_dispatch:
  #   inputs:
  #     tenant:
  #       description: 'Select tenant'
  #       required: true
  #       default: tenant1
  #       type: choice
  #       options:
  #         - tenant1
  #         - tenant2
  #         - tenant3
  #     environment:
  #       description: 'Select environment'
  #       required: true
  #       type: environment
  #       default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo hello > hello.txt
      - name: Upload Packaged Template as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello.txt
          path: hello.txt

  DeployDev:
    strategy:
      matrix:
        tenant: [tenant1, tenant2, tenant3]  # Add more tenants as needed
        # platform: [x86_64, arm64]  # Add more platforms as needed
        # os: [ubuntu-latest, windows-latest]  # Add more OS as needed
        # version: [1, 2, 3]          # Add more versions as needed
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: dev
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Download Packaged Template as Artifact
        uses: actions/download-artifact@v4
        with:
          name: hello.txt
      - name: Run a multi-line script
        run: |
          ls -a

  DeployStaging:
    strategy:
      matrix:
        tenant: [tenant1, tenant2, tenant3]  # Add more tenants as needed
        # platform: [x86_64, arm64]  # Add more platforms as needed
        # os: [ubuntu-latest, windows-latest]  # Add more OS as needed
        # version: [1, 2, 3]          # Add more versions as needed
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    environment:
      name: dev
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Download Packaged Template as Artifact
        uses: actions/download-artifact@v4
        with:
          name: hello.txt
      - name: Run a multi-line script
        run: |
          ls -a

  DeployProd:
    strategy:
      matrix:
        tenant: [tenant1, tenant2, tenant3]  # Add more tenants as needed
        # platform: [x86_64, arm64]  # Add more platforms as needed
        # os: [ubuntu-latest, windows-latest]  # Add more OS as needed
        # version: [1, 2, 3]          # Add more versions as needed
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    environment:
      name: dev
    needs: [DeployStaging]
    steps:
      - uses: actions/checkout@v4
      - name: Download Packaged Template as Artifact
        uses: actions/download-artifact@v4
        with:
          name: hello.txt
      - name: Run a multi-line script
        run: |
          ls -a
